Update to solstice
cyneprepou4uk/NES-Games-Disassembly pull request #8
Opened 2023-02-12 08:25 UTC by 32JP

So I finally got git working, it was mix of my internet being weird yesterday and gtigui being annoying lol.

Anyway, heres the first major update.

2023-02-13 22:12 UTC, cyneprepou4uk commented on Solstice/bank_00.asm
> -; bzk garbage? possible usage at 0x001538
restore this coment

2023-02-13 22:12 UTC, cyneprepou4uk commented on Solstice/bank_00.asm
> -; bzk optimize, 3rd byte is always 00
restore this comment

2023-02-13 22:15 UTC, cyneprepou4uk commented on Solstice/bank_02.asm
> -_off012_A786_03:    ; bzk bug
restore this comment

2023-02-13 22:15 UTC, cyneprepou4uk commented on Solstice/bank_02.asm
> -- D 1 - I - 0x0128A2 04:A892: FE        .byte $FE   ; bzk useless?
restore this comment

2023-02-13 22:39 UTC, cyneprepou4uk requested changes
Too many changes in bank_FF at the same time, the site doesn't load diffs (throws an error), so I can't review then. You need to make smaller updates to this file. Restore it back to original, then keep replacing a thousand lines at a time for example from your modified one.

2023-02-14 21:10 UTC, cyneprepou4uk commented
[5eae4bd](https://github.com/cyneprepou4uk/NES-Games-Disassembly/pull/8/commits/5eae4bd6254cd8807af3a18827f32ec204600541) looks good, keep doing that for the rese of the file

2023-02-14 21:31 UTC, 32JP commented
> [5eae4bd](https://github.com/cyneprepou4uk/NES-Games-Disassembly/pull/8/commits/5eae4bd6254cd8807af3a18827f32ec204600541) looks good, keep doing that for the rest of the file

I'll finish rest on Thursday at earliest, or by weekend.

2023-02-18 16:51 UTC, 32JP commented
Okay this should be fine now, Im done for now unless something comes up

2023-02-18 18:16 UTC, cyneprepou4uk commented on Solstice/bank_FF.asm
> -; bzk garbage, unused room?
restore this comment

2023-02-18 22:09 UTC, merged

2023-02-18 22:11 UTC, cyneprepou4uk commented
Great! Thank you for your contribution, and your patience :)